### ISSUE TITLE
Word spacing issue in english language

### ISSUE THREAD

**Issue by Tanveertts** [abbassiddiqi/mehr#1]
If i am using mahar font and write an english paragraph any where, it is removing word spacing

**Comment by uzairhanfee** [comment]
If I am using Mehar font and write an English paragraph anywhere, it is removing word spacing

**Comment by uzairhanfee** [comment]
@Tanveertts 
**Please Try** 

@font-face {
   font-family: Mehr;
   src: url(//unpkg.com/mehr/mehr.ttf) format('truetype');
   }

* {
   font-family: Arial Narrow, Mehr;
}

**Comment by uzairhanfee** [comment]
@Tanveertts 

**### try the following code**

```
@font-face {
   font-family: Mehr;
   src: url(//unpkg.com/mehr/mehr.ttf) format('truetype');
   }

* {
   font-family: Mehr;


  word-spacing: 2px;
}
```

**Comment by uzairhanfee** [comment]
> If i am using mahar font and write an english paragraph any where, it is removing word spacing

@Tanveertts

### try the following code

@font-face {
   font-family: Mehr;
   src: url(//unpkg.com/mehr/mehr.ttf) format('truetype');
   }

* {
   font-family: Mehr;


  word-spacing: 2px;
}

**Comment by abbassiddiqi** [comment]
If your text contains both Urdu and English, then you can mention a fallback font, which will fix the spacing issue in English text.

```css
body {
    font-family: Mehr, Arial, sans-serif;
}
```

**Comment by uzairhanfee** [comment]
> If your text contains both Urdu and English, then you can mention a fallback font, which will fix the spacing issue in English text.
> 
> ```css
> body {
>     font-family: Mehr, Arial, sans-serif;
> }
> ```

But it is not working.

**Comment by abbassiddiqi** [comment]
You can try this approach:

```html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Urdu English Document</title>
    <style>

        @import url(https://unpkg.com/mehr/mehr-font.css);

        body {
            font-family: Arial, Helvetica, sans-serif;
        }
        
        *[dir="rtl"],
        html[dir="rtl"] > body,
        div[dir="rtl"],
        span[dir="rtl"],
        p[dir="rtl"],
        html[dir="rtl"] * {
            font-family: Mehr !important;
        }

    </style>
</head>

<body>
    <h2 dir="rtl" lang="ur">قومی شاعر</h2>
    <p dir="rtl" lang="ur">علامہ محمد اقبال</p>
    
    <p>Allama Muhammad Iqbal</p>

    <br />

    <p dir="rtl" lang="ur">
        سلیقے سے ہواؤں میں جو خوشبو گھول سکتے ہیں<br />
        ابھی کچھ لوگ باقی ہیں جو اُردو بول سکتے ہیں
    </p>
</body>

</html>
```

Copy this code to a file `index.html` on your desktop and open it in chrome.

Put `dir="rtl"` attribute to any element where you want to show the Urdu content.

**Comment by uzairhanfee** [comment]
> You can try this approach:
> 
> ```
> <!DOCTYPE html>
> 
> <html lang="en">
> 
> <head>
>     <meta charset="UTF-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1.0">
>     <title>Urdu English Document</title>
>     <style>
> 
>         @import url(https://unpkg.com/mehr/mehr-font.css);
> 
>         body {
>             font-family: Arial, Helvetica, sans-serif;
>         }
>         
>         *[dir="rtl"],
>         html[dir="rtl"] > body,
>         div[dir="rtl"],
>         span[dir="rtl"],
>         p[dir="rtl"],
>         html[dir="rtl"] * {
>             font-family: Mehr !important;
>         }
> 
>     </style>
> </head>
> 
> <body>
>     <h2 dir="rtl" lang="ur">قومی شاعر</h2>
>     <p dir="rtl" lang="ur">علامہ محمد اقبال</p>
>     
>     <p>Allama Muhammad Iqbal</p>
> 
>     <br />
> 
>     <p dir="rtl" lang="ur">
>         سلیقے سے ہواؤں میں جو خوشبو گھول سکتے ہیں<br />
>         ابھی کچھ لوگ باقی ہیں جو اُردو بول سکتے ہیں
>     </p>
> </body>
> 
> </html>
> ```
> 
> Copy this code to a file `index.html` on your desktop and open it in chrome.
> 
> Put `dir="rtl"` attribute to any element where you want to show the Urdu content.

Thanks for your help. Jazakallah
