### ISSUE TITLE
Space Problem in english word

### ISSUE THREAD

**Issue by Gaazi** [abbassiddiqi/mehr#5]
Assalamu Alaikum
please upload Meher Nastaliq Verson 2 and Update
this issue will be fix

[mehr nastaliq web font v 2.0.zip](https://github.com/abbassiddiqi/mehr/files/13304375/mehr.nastaliq.web.font.v.2.0.zip)

i download this free version from official website (MehrType.com) 
thank

**Comment by abbassiddiqi** [comment]
The font is updated to `v2.0`.
